require("opts.oil")
require("opts.kanagawa")
require("opts.lualine")
require("opts.buffer_manager")
require("opts.dashboard-nvim")
require("opts.bookmarks")
require("opts.treesitter")
require("opts.whichkey")
