dofile("opts/oil.lua")
dofile("opts/kanagawa.lua")
dofile("opts/lualine.lua")
dofile("opts/buffer_manager.lua")
dofile("opts/dashboard-nvim.lua")
dofile("opts/bookmarks.lua")
dofile("opts/treesitter.lua")
dofile("opts/whichkey.lua")
